# some glass stuff (picom)
backend = "glx";
vsync = true;

blur: {
  method = "dual_kawase";
  strength = 7;
}

corner-radius = 12;

active-opacity = 0.95;
inactive-opacity = 0.85;

shadow = true;
shadow-radius = 20;
shadow-opacity = 0.4;

# ignore these
blur-background-exclude = [
  "window_type = 'desktop'",
  "class_g = 'slop'"
];
